language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: RCucD1OLWUupSUsWfcRw4cxtLK5lUWbSeOC/1BAKwWkPKiRH4WReNupwKxWjK07x35CEN48CpY9FaRWRysk4LUl3Si+OMg5Jf+RfQcPGg1scP7+hagzR5fhKUrHj8rsR7Rye3YIjyE7RzAgUOOO57z/sC4HdJ0VkTqJJqcQwWOALqEz22UFxAc07tUiwFnR7ONodWNfHYMlDVBbk+mz20ZfuIF6i44RDenjqo7A591rA+068C6AKXlmrWjh9llX8LKhx6subj0oAasgq5mGabgr2ee+c3o68NQ7wla7vrdMbYtCXzCs/mifudtRmSxjnLxwh1w71RSJ4ixP2xlFgUWdkPQgMlbL437wVNK8thc/ajI5IZkylo5VPh41r9aVzoSZksY0G6SGXvL/0FuoY7uxzPXc1GcY+zYwnZnd1wubRWePBLbuQOEi6KwjHPXoigfcdwWQ7ZmCfa8etPt0vwwjdQMi1AmESvPZ4RdihZEQcslDeCK1UvTfZLwbrjUjY0s/4hy2RK0HF/RgOTuayFu0m2JSuAN3VnlC7Tg7VL5DQnNVWnYGVQ+r95NxsNJYJBCGVgMu7MJVTEKGIF5Joz8g0zNV/p+r0xDzoxd5BzpYVf2JnQzq5pvulfqE14OM1BkXQEV6TKzZT02j8JcMLTgRlyVAWKNWu2FxM6qThanY=
  app: blog-api
  on:
    repo: bryg217/blog-api
